### ISSUE TITLE
Flutter : DioError [DioErrorType.response]: Http status error [403]

### ISSUE THREAD

**Issue by helenapc** [JulioCGMC/google_translator#2]
when the widget runs it does not translate the text and that error appears.

I/flutter (25290): DioError [DioErrorType.response]: Http status error [403]

I/flutter (25290): Source stack:
I/flutter (25290): #0      DioMixin.fetch .............................. package:dio/src/dio_mixin.dart:473
I/flutter (25290): #1      DioMixin.request .............................. package:dio/src/dio_mixin.dart:468
I/flutter (25290): #2      DioMixin.post .............................. package:dio/src/dio_mixin.dart:91
I/flutter (25290): #3      GoogleTranslatorRepository.translate .............................. 
            package:google_translator/repositories/google_translator_repository.dart:23
I/flutter (25290): #4      GoogleTranslatorController.translateText .............................. 
            package:google_translator/controllers/google_translator_controller.dart:45
I/flutter (25290): #5      TranslateText.translate .............................. package:google_translator/extensions/text_extension.dart:11
I/flutter (25290): #6      BoxInfo.build .............................. package:ff2/widget/group_box_info.dart:78
I/flutter (25290): #7      StatelessElement.build .............................. package:flutter/…/widgets/framework.dart:4827
I/flutter (25290): #8      ComponentElement.performRebuild .............................. package:flutter/…/widgets/framework.dart:4754
I/flutter (25290): #9      Element.rebuild .............................. package:flutter/…/widgets/framework.dart:4477
I/flutter (25290): #10     ComponentElement._firstBuild .............................. package:flutter/…/widgets/framework.dart:4735

Windows 10.
Android 11.
google_translator: ^1.0.0
Flutter SDK (LSP) : 2.10.3 • channel stable
Dart SDK version: 2.16.1 (stable) • DevTools 2.9.2

**Comment by JulioCGMC** [comment]
Hello, actually this package is no longer maintained, instead we decided to switch to a more generic package, try: https://pub.dev/packages/universal_translator
